# Generated by Django 2.1.15 on 2020-03-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellido')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefono')),
                ('address', models.CharField(max_length=50, verbose_name='Direccion')),
            ],
        ),
    ]
